### ISSUE TITLE
2.x - Batch requests using /me segment generate incorrect URLs

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-php-core#126]
Batch requests are not replacing the `/users/me-token-to-replace` in the request URIs. This is with microsoft/microsoft-graph 2.0.0-RC16 and microsoft/microsoft-graph-core 2.0.0-RC9.

For example:

```php
$userRequest = $graphClient->me()->toGetRequestInformation();
$userRequestItem = new BatchRequestItem($userRequest);
$batchRequestContent = new BatchRequestContent([$userRequestItem]);

$batchRequestBuilder = new BatchRequestBuilder($graphClient->getRequestAdapter());
/** @var BatchResponseContent $batchResponse */
$batchResponse = $batchRequestBuilder->postAsync($batchRequestContent)->wait();
```

This will result in a payload like this:

```json
{
    "requests": [
        {
            "id": "c4d3c412-80f8-4678-ab89-4028b589f3ba",
            "method": "GET",
            "url": "/users/me-token-to-replace",
            "headers": {
                "accept": "application/json"
            }
        }
    ]
}
```

**Comment by Ndiritu** [comment]
@andrueastman @rkodev @samwelkanda this might be affecting your SDKs as well. We need to replace `/users/me-token-to-replace` when initializing a Batch request item URL from a Request information object.
cc: @baywet @shemogumbe @isvargasmsft

**Comment by isvargasmsft** [comment]
CC: @sebastienlevert @maisarissi @CarolKigoonya
