### ISSUE TITLE
GraphClientFactory for PHP

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-php-core#18]
The GraphClientFactory will give SDK users the option to create and define their own HTTP client configuration and pass it to Graph() to be used for requests.

Consider support for arbitrary HttpClients so that customer can bring their own clients to use in our GraphClient.

Reference:
https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/GraphClientFactory.md 

Related to:
microsoftgraph/msgraph-sdk-php#328 , microsoftgraph/msgraph-sdk-php#339 , microsoftgraph/msgraph-sdk-php#283 , microsoftgraph/msgraph-sdk-php#232 

Task breakdown:
- [x] Design doc written and reviewed
- [x] Implement HttpClientFactory
- [x] Make changes to GraphRequest classes to remove HTTP client concerns
- [x] Update tests
- [x] Document breaking changes in an upgrade guide

[AB#8906](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8906)

**Comment by Ndiritu** [comment]
Added to v2-preview release
