### ISSUE TITLE
Retry handler support

### ISSUE THREAD

**Issue by roinochieng** [microsoftgraph/msgraph-sdk-php-core#24]
[AB#9685](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9685)

**Comment by krasa** [comment]
bump...
I am often getting random GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 15000 milliseconds with 0 bytes received

**Comment by Ndiritu** [comment]
@krasa kindly share what version of the SDK you're using

**Comment by krasa** [comment]
```
PHP Version 8.1.2 
microsoft/microsoft-graph 1.65.0
guzzlehttp/guzzle 7.4.2
```

Dunno what is the difference between https://github.com/microsoftgraph/msgraph-sdk-php and this, but you might still consider this case when you are implementing it.

**Comment by Ndiritu** [comment]
We have implemented a Retry Handler and bunch of other handlers in our 2.0-Release Candidate.
Feel free to [try it out](https://github.com/microsoftgraph/msgraph-sdk-php/issues/943)
