### ISSUE TITLE
Telemetry handler support

### ISSUE THREAD

**Issue by roinochieng** [microsoftgraph/msgraph-sdk-php-core#25]
[AB#9693](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9693)

**Comment by MIchaelMainer** [comment]
https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/TelemetryHandler.md

We will require this to help us get better information about SDK usage. We will want to fully implement this spec.

**Comment by Ndiritu** [comment]
Added to [2.0-RC5](https://github.com/microsoftgraph/msgraph-sdk-php/issues/943)
