### ISSUE TITLE
Add missing OData type classes

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/msgraph-sdk-php-core#29]
Following efforts to add static analysis to identify missing classes, we need to implement missing OData type classes or map those to existing PHP types e.g. `TimeOfDay`, `Decimal` etc 
[AB#10594](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10594)

**Comment by SilasKenneth** [comment]
Closes when #48 is merged
