### ISSUE TITLE
Please provide an example/documentation for batch requests

### ISSUE THREAD

**Issue by dbollaer** [microsoftgraph/msgraph-sdk-php-core#88]
Hello,

I am trying to use BatchRequestBuilder. Which was added here: https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/72
But I am afraid it's not very clear to me.
I tried reading the unit tests, but I am getting bad request exceptions.

Could you please provide an example where you send a a couple of post requests and handle the responses after there finished.

Thank you for taking the time to look at this request.

**Comment by Ndiritu** [comment]
@dbollaer please check out our latest [code samples](https://github.com/microsoftgraph/msgraph-sdk-php/blob/feat/kiota-preview/docs/Examples.md#batching-requests). The samples work with our latest release [`2.0.0-RC14`](https://github.com/microsoftgraph/msgraph-sdk-php/releases/tag/2.0.0-RC14) which contains some bug fixes for batch requests.
Happy to get more feedback.
