### ISSUE TITLE
`PageIterator`  instantiation suggested improvement

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/msgraph-sdk-php-core#95]
We currently init a Page Iterator by passing the type of the collection response to be used to deserialize responses from subsequent next page requests e.g. to page through a message collection

```php
$messageCollection = $graphServiceClient->usersById(USER_ID)->messages()->get()->wait();
$iterator = new PageIterator($messageCollection , $requestAdapter, [MessageCollectionResponse::class, 'createFromDiscriminatorValue']);
```

We expect the developer to pass in `[MessageCollectionResponse::class, 'createFromDiscriminatorValue']` which exposes our implementation details to devs which could lead to errors.

Could we abstract this by deriving the constructor parsable by checking the type of the initial collection response e.g. `$messageCollection`

cc: @SilasKenneth, @shemogumbe, @isvargasmsft

**Comment by isvargasmsft** [comment]
Thank you for this explanation @Ndiritu. Could you share how the experience for the developer would look like, please?

**Comment by Ndiritu** [comment]
The new experience would be

```php
$messageCollection = $graphServiceClient->usersById(USER_ID)->messages()->get()->wait();
// removes the need to pass [MessageCollectionResponse::class, 'createFromDiscriminatorValue']
$iterator = new PageIterator($messageCollection , $requestAdapter);
```

We could also add a `pageIterator` method to the Graph client like Go is currently doing and make the experience:

```php

$messageCollection = $graphServiceClient->usersById(USER_ID)->messages()->get()->wait();
// removes need to pass the $requestAdapter
$iterator = $graphServiceClient->pageIterator($messageCollection);
```

**Comment by isvargasmsft** [comment]
Thank you @Ndiritu. I like the second experience better. It feels more intuitive. 

@SilasKenneth, what do you think?

**Comment by SilasKenneth** [comment]
It makes sense to reduce the number of places a user might make mistakes when using the page iterator.

👍🏾 +1

> Thank you @Ndiritu. I like the second experience better. It feels more intuitive.
> 
> @SilasKenneth, what do you think?
